resources:
  repositories:
    - repository: topaz-conan-dev
      type: github
      endpoint: TopazLabs
      name: TopazLabs/topaz-conan-dev
      ref: feature/upload
    - repository: nv-codec-headers
      type: github
      endpoint: TopazLabs
      name: FFmpeg/nv-codec-headers
      ref: refs/tags/n13.0.19.0

parameters:
  - name: version
    displayName: 'VERSION'
    type: string
    default: '0.0.0'
  - name: publish
    displayName: 'PUBLISH'
    type: boolean
    default: false
  - name: windows
    displayName: 'Windows (2022)'
    type: boolean
    default: true
  - name: windows_arm
    displayName: 'Windows ARM64 (2022)'
    type: boolean
    default: true
  - name: linux
    displayName: 'Linux (Ubuntu 22.04)'
    type: boolean
    default: true
  - name: mac
    displayName: 'MacOS'
    type: boolean
    default: true

variables:
  - name: VERSION
    value: ${{ parameters.version }}
  - ${{ if eq(parameters.publish, true) }}:
    - name: PUBLISH
      value: 'true'
    - ${{ if not(eq(parameters.version, '0.0.0'))}}:
      - name: TAGABLE
        value: 'true'
    - ${{ if eq(parameters.version, '0.0.0')}}:
      - name: TAGABLE
        value: ''
  - ${{ if eq(parameters.publish, false) }}:
    - name: PUBLISH
      value: ''

stages:
- stage: Build
  condition: or(eq(variables['TAGABLE'], 'true'), eq(variables['PUBLISH'], ''))
  jobs:
  - ${{ if eq(parameters.windows, true) }}:
    - job: Windows2022
      workspace:
        clean: all
      pool:
          name: Default
          demands:
            - Agent.Name -equals Medusa
      steps:
        - template: win.yml
          parameters:
                arch: AMD64
  - ${{ if eq(parameters.windows_arm, true) }}:
    - job: Windows2022ARM
      workspace:
        clean: all
      pool:
        name: 'WinARM'
      steps:
        - template: win.yml
          parameters:
                arch: ARM64

  - ${{ if eq(parameters.linux, true) }}:
    - job: Ubuntu22_04
      workspace:
        clean: all
      pool:
        name: UbuntuVMSS
      steps:
        - template: ubuntu.yml

  - ${{ if eq(parameters.mac, true) }}:
    - job: Mac
      workspace:
        clean: all
      pool:
        name: Mac
        demands:
        - AppleSilicon
      steps:
        - template: macos.yml
- ${{ if eq(parameters.publish, true) }}:
  - stage: Tag
    condition: succeeded('Build')
    jobs:
    - job: Tagging
      steps:
        - checkout: self
          persistCredentials: true
        - bash: |
            cd "$(Build.SourcesDirectory)/"
            git tag "topaz-v$(VERSION)"
            git push --tags  
          displayName: Tag
          
      pool: 
        name: UbuntuVMSS