parameters:
  - name: version
    displayName: 'VERSION'
    type: string
    default: '0.0.0'
  - name: publish
    displayName: 'PUBLISH'
    type: boolean
    default: false
  - name: windows
    displayName: 'Windows (2019)'
    type: boolean
    default: true
  - name: linux
    displayName: 'Linux (Ubuntu 22.04)'
    type: boolean
    default: true
  - name: mac
    displayName: 'MacOS'
    type: boolean
    default: true
  - name: nv-codec-headers
    displayName: 'NV CODEC HEADERS version(tag)'
    type: string
    default: n13.0.19.0
  - name: build_note
    displayName: 'Build Note'
    type: string
    default: "."
  - name: azure_tags
    displayName: 'Additional Azure tags'
    type: object
    default: []

variables:
  - group: "Secrets"
  - name: VERSION
    value: ${{ parameters.version }}
  - ${{ if eq(parameters.publish, true) }}:
    - name: PUBLISH
      value: 'true'
    - ${{ if not(eq(parameters.version, '0.0.0'))}}:
      - name: TAGABLE
        value: 'true'
    - ${{ if eq(parameters.version, '0.0.0')}}:
      - name: TAGABLE
        value: ''
  - ${{ if eq(parameters.publish, false) }}:
    - name: PUBLISH
      value: ''
  - name: BUILD_NOTE
    value: ${{ parameters.build_note }}

resources:
  repositories:
    - repository: pipeline-helper
      type: github
      endpoint: TopazLabs (1)
      name: TopazLabs/pipeline-helper
      ref: feature/upgrade
    - repository: topaz-conan-dev
      type: github
      endpoint: TopazLabs
      name: TopazLabs/topaz-conan-dev
      ref: feature/upload
    - repository: nv-codec-headers
      type: github
      endpoint: TopazLabs
      name: FFmpeg/nv-codec-headers
      ref: "refs/tags/${{ parameters.nv-codec-headers }}"


stages:
- stage: Build
  condition: or(eq(variables['TAGABLE'], 'true'), eq(variables['PUBLISH'], ''))
  jobs:
  - ${{ if eq(parameters.windows, true) }}:
    - job: Windows2019
      workspace:
        clean: all
      pool:
          name: Default
          demands:
            - Agent.Name -equals Medusa
      steps:
        - template: win.yml

  - ${{ if eq(parameters.linux, true) }}:
    - job: Ubuntu22_04
      workspace:
        clean: all
      pool:
        name: UbuntuVMSS
      steps:
        - template: ubuntu.yml

  - ${{ if eq(parameters.mac, true) }}:
    - job: Mac
      workspace:
        clean: all
      pool:
        name: Mac
        demands:
        - AppleSilicon
      steps:
        - template: macos.yml

- ${{ if eq(parameters.publish, true) }}:
  - stage: Tag
    condition: succeeded('Build')
    jobs:
    - job: Tagging
      steps:
        - checkout: self
          persistCredentials: true
        - bash: |
            cd "$(Build.SourcesDirectory)/FFmpeg"

            echo "Set User for Github"
            git config --global user.email "dev@topazlabs.com"
            git config --global user.name "Topaz Labs Build Pipeline"

            if [ "${{ parameters.build_note }}" = "." ]; then
              note="- $(Build.RequestedFor)"
            else
              note="${{ parameters.build_note }} - $(Build.RequestedFor)"
            fi

            git tag -a "v$(VERSION)" -m "$note"
            git push --tags
          displayName: Tag (Github)
        - bash: |
            cleaned_version="${VERSION//+/\-}"
            echo "##vso[build.addbuildtag]$cleaned_version"
          displayName: 'Tag Version (Azure)'
        - ${{ if ne(length(parameters.azure_tags), 0)}}:
          - bash: |
              tags=$(echo '${{ convertToJson(parameters.azure_tags) }}' | jq -r '.[]')
              for tag in $tags; do
                echo "##vso[build.addbuildtag]$tag"
              done
            displayName: 'Azure Tags'